### ISSUE TITLE
Hexgloop's mind jars have no compat with Make Genie spell

### ISSUE THREAD

**Issue by candyCalc** [miyucomics/hexical#11]
Using a [Hexgloop](https://github.com/SamsTheNerd/HexGloop) Mind in a Jar instead of a villager in the Make Genie spell returns this error.
![image](https://github.com/miyucomics/hexical/assets/109626643/c8efb244-4f01-4213-b461-ae3f894b40a7)

Reproduction:
1. Flay a journeyman or higher villager into a Flayer's Pedestal with an Empty Jar on it.
2. Add the resulting Mind in Jar item entity to the stack
3. Add the media item entity to the stack
4. Hold an empty Hand Genie Lamp in the offhand
5. Cast Make Genie

Expected result:
&ensp;Mind in a Jar turns into an Empty Jar and the genie lamp's media battery is set.

Actual result:
&ensp;Sends the error message "Make Genie expected a villager at index 1 of the stack, but got Mind in a Jar" in chat.

Issue on Hexgloop's github: https://github.com/SamsTheNerd/HexGloop/issues/66

**Comment by miyucomics** [comment]
After some recent changes to how the spell works and its lore to be more useful, I don't think compatibility with minds in jars is thematically appropriate so I'll close this issue.
