### ISSUE TITLE
Using Erase Item on Archgenie Lamp returns unusable lamp

### ISSUE THREAD

**Issue by candyCalc** [miyucomics/hexical#12]
Using the [Erase Item](https://hexcasting.hexxy.media/v/latest/1.19/en_us/#patterns/spells/hexcasting@hexcasting:erase) spell on an Archgenie Lamp returns an empty Archgenie Lamp which cannot be refilled with the Make Genie spell.
![archgenie-bug](https://github.com/miyucomics/hexical/assets/109626643/4e3e92bb-5799-4416-9173-8bd07a8ce5e2)

Reproduction:
1. Hold an Archgenie Lamp in your offhand
2. Cast Erase Item

Expected result:
&ensp;The Archgenie Lamp turns into an empty Hand Genie Lamp

Actual result:
&ensp;The Archgenie Lamp turns into an empty Archgenie Lmap

**Comment by miyucomics** [comment]
This is a bug that has been fixed in the current development version. It will be fixed in the next released version.
