### ISSUE TITLE
[Suggestion] Spell to activate an Archgenie Lamp

### ISSUE THREAD

**Issue by candyCalc** [miyucomics/hexical#13]
A spell to activate an Archgenie Lamp; the opposite of Terminate Archgenie. Commence Archgenie.

Can be casted by a casting device or staff to activate the Archgenie Lamp in your mainhand/offhand, or by a lamp to activate itself similar to Herme's.

While dropping or placing the lamp in a chest can disable it, it may need to throw an error on a finale to prevent players from making Archgenie Lamps you can't deactivate by hand.

This would be useful in three scenarios:
1. To activate the lamp after Terminate Archgenie to "undo" the termination,
2. To make Archgenie Lamps that disable any current archgenies, serve a purpose, then resume the lamp it disabled,
3. And to make lamps that automatically recharge themselves. A cypher that erases then re-craft itself can bypass it's inability to recharge. A similar (albeit more complicated) solution could be employed with Archgenie Lamps. The lamp could clear itself, teleport a villager and media nearby and cast Make Genie to refill itself (assuming the lamp is kept in the offhand). Currently if this was done the player would need to manually re-activate the lamp every time it resets itself this way.

![image](https://github.com/miyucomics/hexical/assets/109626643/cce6b859-95f4-4d3d-b571-b7692f500854)
A possible pattern for Commence Archgenie

**Comment by miyucomics** [comment]
I haven't added this because there can only be one lamp active at a time. Which lamp would this spell activate? For your second idea, how do you know that the deactivating lamp won't just activate itself again?

**Comment by candyCalc** [comment]
The spell could check for lamps in the order: item in offhand, item in mainhand, item that casted the spell. Then, by activating the first one found the second idea could work, provided the other lamp was kept in your offhand. This would be weird though since similar things in hex check for your mainhand before your offhand. You could still do the second idea if the order was consistent with hex casting by using hexgloop's hotbar patterns as long as the check for the lamp that cast the spell remained the last check.

**Comment by candyCalc** [comment]
actually maybe it should use the order that Place Block uses so it can target a lamp in any given inventory slot

**Comment by miyucomics** [comment]
I have added it.
