### ISSUE TITLE
Attempting to conjure a rank-zero staff results in an unusable item

### ISSUE THREAD

**Issue by beholderface** [miyucomics/hexical#15]
All it does when you try to activate it is make the mishap sound, regardless of what hex you gave it. The conjuration spell does not know that a rank-zero staff does not work, so it just eats your media without complaint.
I suggest making the spell mishap if you give it a zero for rank.

**Comment by miyucomics** [comment]
I added a mishap so it is now fixed in the development version and will be fixed in the next released version.
