### ISSUE TITLE
[Suggestion] Allow the archlamp to be toggled by rclicking it in your inventory

### ISSUE THREAD

**Issue by beholderface** [miyucomics/hexical#27]
Would be a nice little feature that makes it slightly smoother to use for things you may not want active 100% of the time.

**Comment by miyucomics** [comment]
I would love to add this feature but it seems the `ItemStack#onClicked` method ( which the bundle uses ) only gets called when already holding another item stack so I don't think there is much I can do without an annoying mixin.
