### ISSUE TITLE
Book typo/mistranslation in telepathy chapter (Typo)

### ISSUE THREAD

**Issue by Stick404** [miyucomics/hexical#30]
In the telepathy chapter, the `Telepathic Reflection` says it can return null/number, however in the last update it was changed to be -1/ticks you hold down
![image](https://github.com/user-attachments/assets/4f34b455-4fae-481f-9194-6c8a8900f12a)

**Comment by miyucomics** [comment]
This has already been fixed, it's just awaiting a release to become public.
