### ISSUE TITLE
Conjured Staff places Conjured Blocks instead of Mage Blocks

### ISSUE THREAD

**Issue by TTwicee** [miyucomics/hexical#4]
Trying to use Conjure Mage Block with a Conjured Staff produces a regular conjured block instead. Conjured Staves also can't modify mage blocks.

**Comment by miyucomics** [comment]
I tried it and it does produce mage blocks, although I was able to reproduce it not applying modifiers. I'll look into that. For now, are you sure you drew it properly?

**Comment by TTwicee** [comment]
Sorry! Slight mistake: on testing again, I found it does produce mage blocks, however they don't match the player's pigment color and cannot be modified with the conjured staff.

**Comment by miyucomics** [comment]
Yep I've reproduced that exact issue. I'll fix it by the next version! Thank you for reporting!

**Comment by miyucomics** [comment]
This has been successfully fixed! It'll be ready in the next update.
