### ISSUE TITLE
Akashic Terminal unable to read/write from shelves when connected via akashic record

### ISSUE THREAD

**Issue by M1tht1c** [miyucomics/hexical#8]
Pretty much as the title says, since the AkashicFloodfiller function doesn't flood through the akashic record block, the terminal can't find shelves where the terminal is the only route. The same is true for the record, if a shelf is connected through the terminal, it can't be seen by the record, but is still considered connected by the terminal.

This could make for a neat permissions system, with shared and private sections of a library, but I figured since it probably wasn't intentional, I should make an issue for it.

**Comment by miyucomics** [comment]
It's fixed so that it can flood through the terminal now. Out of curiosity, how did you get this version of the addon? Did you build it yourself?

**Comment by M1tht1c** [comment]
Yeah, I had to do it with the base (1.19) mod recently to get it to use the latest version of cloth, so I've just been checking out what all the addons have been working on.
